name: GitHub Pages Publish
permissions:
  contents: write

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0

      - name: Setup Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '18'

      - name: Cache dependencies
        uses: actions/cache@v3.2.6
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('styles/package-lock.json') }}
          restore-keys: npm-

      - name: Install CSS build dependencies
        run: npm ci --ignore-scripts
        working-directory: styles
      
      - name: Fix node-sass
        run: npm rebuild node-sass
        working-directory: styles

      - name: Build Bulma CSS with kroxy customisations
        run: npm run css-build
        working-directory: styles
  
      - name: Copy build
        run: |
          ls styles/css && cp -R static build && cp styles/css/mystyles.css build/mystyles.css
      
      - name: Deploy static dir to Github Pages gh-pages branch 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages
